version: '3.8'

services:
  db:
    image: postgres
    restart: always
    ports:
      - "5433:5433"
    environment:
      POSTGRES_USERNAME: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: restaurant